name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install NPM dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Setup WordPress environment
      run: npm run env:start

    - name: Run Playwright tests
      run: npm run test:e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: report
        path: tests/e2e/artifacts/report
        retention-days: 30
